### ISSUE TITLE
Ucapakan Terima Kasih dan Sedikit Saran

### ISSUE THREAD

**Issue by jefrydco** [muhammadabdis/highlight-code#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Abdis. Mas juga sudah menggunakan Tailwind CSS sebagai kerangka kerja CSS nya. Luar biasa Mas!

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni

1. Menambahkan Tautan ke Demo Aplikasi
Menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

2. Belum ada Fitur Simpan Kode(?)
Saya coba cek, setelah user login, user belum bisa melihat kode yang pernah disimpan ya Mas?

Kalau ada yang bingung, jangan segan-segan untuk bertanya ya dan semangat selalu! :muscle:

**Comment by muhammadabdis** [comment]
Terima kasih Mas Jefry, semoga bisa menjadi pelajaran buat saya
